import type { BrandingSettings, DemoUser, Invoice, PaymentSettings } from "../types";
export const demoUser: DemoUser = { id: "demo-founder", email: "founder@grassbuddy.app", name: "GrassBuddy Founder" };
export const defaultPaymentSettings: PaymentSettings = { stripeLink: "https://buy.stripe.com/demo-grassbuddy", paypalLink: "https://paypal.me/grassbuddy-demo", preferredProvider: "stripe" };
export const defaultBranding: BrandingSettings = { businessName: "Green Ridge Lawn Co." };
export const blankInvoice = (): Invoice => ({ id: crypto.randomUUID(), userId: demoUser.id, businessName: defaultBranding.businessName, customer: { id: crypto.randomUUID(), name: "", phone: "", email: "", address: "" }, kind: "residential", invoiceNumber: "GB-" + new Date().getFullYear() + "-" + Math.floor(Math.random() * 900 + 100), invoiceDate: new Date().toISOString().slice(0, 10), dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString().slice(0, 10), items: [{ id: crypto.randomUUID(), description: "Lawn mowing and edging", quantity: 1, price: 85 }], taxRate: 0, discount: 0, notes: "Thank you for trusting us with your property.", terms: "Payment due by the due date listed above.", status: "unpaid", createdAt: new Date().toISOString() });
export const seedInvoices: Invoice[] = [
  { ...blankInvoice(), id: "inv-demo-1001", invoiceNumber: "GB-2026-1001", customer: { id: "cust-1", name: "Maya Thompson", phone: "(312) 555-0178", email: "maya@example.com", address: "1842 Oak Bend Dr, Austin, TX" }, items: [{ id: "i1", description: "Weekly lawn service", quantity: 1, price: 95 }, { id: "i2", description: "Mulch refresh", quantity: 3, price: 42 }], taxRate: 0, discount: 10, status: "paid" },
  { ...blankInvoice(), id: "inv-demo-1002", invoiceNumber: "GB-2026-1002", customer: { id: "cust-2", name: "Northline Dental Group", phone: "(773) 555-0199", email: "ops@northline.example", address: "2210 Market St, Chicago, IL" }, kind: "commercial", items: [{ id: "i3", description: "Commercial landscape maintenance", quantity: 1, price: 420 }], taxRate: 3.25, discount: 0, status: "unpaid" }
];
